//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.ServiceHBD {
    using System.Data;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="ServiceHBD.WSLerAtendimentosSoap")]
    public interface WSLerAtendimentosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/RetornarUltimoRegistro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RetornarUltimoRegistro(string str_Unidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/RetornarAtendimentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RetornarAtendimentos(string UltimoRegistro, int NumeroLinhas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GravarAtendimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GravarAtendimento(string m_strUnidade, System.Data.DataSet m_oDsDados);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLerAtendimentosSoapChannel :  ServiceHBD.WSLerAtendimentosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLerAtendimentosSoapClient : System.ServiceModel.ClientBase<ServiceHBD.WSLerAtendimentosSoap>, ServiceHBD.WSLerAtendimentosSoap {
        
        public WSLerAtendimentosSoapClient() {
        }
        
        public WSLerAtendimentosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLerAtendimentosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLerAtendimentosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLerAtendimentosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetornarUltimoRegistro(string str_Unidade) {
            return base.Channel.RetornarUltimoRegistro(str_Unidade);
        }
        
        public System.Data.DataSet RetornarAtendimentos(string UltimoRegistro, int NumeroLinhas) {
            return base.Channel.RetornarAtendimentos(UltimoRegistro, NumeroLinhas);
        }
        
        public bool GravarAtendimento(string m_strUnidade, System.Data.DataSet m_oDsDados) {
            return base.Channel.GravarAtendimento(m_strUnidade, m_oDsDados);
        }
    }
}
