//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsETL.SrvPacHBD
{
    using System.Data;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://microsoft.com/webservices/", ConfigurationName = "SrvPacHBD.LerPacientesWPDSoap")]
    public interface LerPacientesWPDSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/RetornarUltimoRegistro", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        string RetornarUltimoRegistro(string str_Unidade);

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/RetornarPacientes", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Data.DataSet RetornarPacientes(string UltimoRegistro, int NumeroLinhas, string strConnHIS, string strScheHIS);

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/RetornarPacientesConciliacao", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Data.DataSet RetornarPacientesConciliacao(string m_DataDe);

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/GravarPaciente", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        bool GravarPaciente(string m_strUnidade, System.Data.DataSet m_oDsDados);

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LerPacientesWPDSoapChannel : WindowsETL.SrvPacHBD.LerPacientesWPDSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LerPacientesWPDSoapClient : System.ServiceModel.ClientBase<WindowsETL.SrvPacHBD.LerPacientesWPDSoap>, WindowsETL.SrvPacHBD.LerPacientesWPDSoap
    {

        public LerPacientesWPDSoapClient()
        {
        }

        public LerPacientesWPDSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public LerPacientesWPDSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LerPacientesWPDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LerPacientesWPDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string RetornarUltimoRegistro(string str_Unidade)
        {
            return base.Channel.RetornarUltimoRegistro(str_Unidade);
        }

        public System.Data.DataSet RetornarPacientes(string UltimoRegistro, int NumeroLinhas, string strConnHIS, string strScheHIS)
        {
            return base.Channel.RetornarPacientes(UltimoRegistro, NumeroLinhas, strConnHIS, strScheHIS);
        }

        public System.Data.DataSet RetornarPacientesConciliacao(string m_DataDe)
        {
            return base.Channel.RetornarPacientesConciliacao(m_DataDe);
        }

        public bool GravarPaciente(string m_strUnidade, System.Data.DataSet m_oDsDados)
        {
            return base.Channel.GravarPaciente(m_strUnidade, m_oDsDados);
        }

    }
}

