//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsETL.SrvGravarPacHBD
{
    using System.Data;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://microsoft.com/webservices/", ConfigurationName = "SrvGravarPacHBD.WSGravarPacientesSoap")]
    public interface WSGravarPacientesSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/RetornarUltimoRegistro", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        string RetornarUltimoRegistro(string str_Unidade);

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/RetornarPacientes", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Data.DataSet RetornarPacientes(string str_Unidade, string UltimoRegistro, int NumeroLinhas);

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/GravarPacientes", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        bool GravarPacientes(string m_strUnidade, System.Data.DataSet m_oDsDados);

        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.com/webservices/RetornarConciliacaoPacientes", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Data.DataSet RetornarConciliacaoPacientes(string str_Unidade, int NumeroLinhas);

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSGravarPacientesSoapChannel : WindowsETL.SrvGravarPacHBD.WSGravarPacientesSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSGravarPacientesSoapClient : System.ServiceModel.ClientBase<WindowsETL.SrvGravarPacHBD.WSGravarPacientesSoap>, WindowsETL.SrvGravarPacHBD.WSGravarPacientesSoap
    {

        public WSGravarPacientesSoapClient()
        {
        }

        public WSGravarPacientesSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public WSGravarPacientesSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WSGravarPacientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WSGravarPacientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string RetornarUltimoRegistro(string str_Unidade)
        {
            return base.Channel.RetornarUltimoRegistro(str_Unidade);
        }

        public System.Data.DataSet RetornarPacientes(string str_Unidade, string UltimoRegistro, int NumeroLinhas)
        {
            return base.Channel.RetornarPacientes(str_Unidade, UltimoRegistro, NumeroLinhas);
        }

        public bool GravarPacientes(string m_strUnidade, System.Data.DataSet m_oDsDados)
        {
            return base.Channel.GravarPacientes(m_strUnidade, m_oDsDados);
        }

        public DataSet RetornarConciliacaoPacientes(string str_Unidade, int NumeroLinhas)
        {
            return base.Channel.RetornarConciliacaoPacientes(str_Unidade, NumeroLinhas);
        }
    }
}

